# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PluginQgisJDS
                                 A QGIS plugin
 Merupakan plugin qgis untuk keperluan opd di provide dari JDS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-10-28
        copyright            : (C) 2022 by Misdan Wijaya
        email                : jds.dataengineer@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PluginQgisJDS class from file PluginQgisJDS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .plugin_qgis_jds import PluginQgisJDS
    return PluginQgisJDS(iface)
